### ISSUE TITLE
合并 nimble 上游的修改后，controller 似乎运行不正常

### ISSUE THREAD

**Issue by greedyhao** [RT-Thread-packages/nimble#11]
https://github.com/greedyhao/nimble

目前在这个仓库已经合并到了上游的 5271e1f，nrf5x 编译可能需要增加 `--specs=nosys.specs` 参数
目前 host 在 ab32vg1 上测试是正常的，但是加上 controller 后，在 nrf52832 上无法运行 ble 的 demo

**Comment by hyhkjiy** [comment]
https://github.com/greedyhao/nimble/pull/1

**Comment by greedyhao** [comment]
https://github.com/RT-Thread-packages/nimble/pull/12
